#ifndef __CORE_ST_H
#define __CORE_ST_H
/**
 * Declaration of string table map
 * Derived from /wrk/safari/cvs/lumimaja/src/core/core.rc2
 * Generated by ../src/core/rc2cpp.pl
 *
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
 * Changes made to this file will be lost when the
 * file is regenerated.
 *
 * Note: The contents of this file is not needed for MFC builds but
 * it does not seem possible to conditionally exclude it from these.
 *
 */

#if !defined(_WIN32) || defined(__WX__)
#include <map>
#include "../os/typedefs.h" // for definition of TCHAR
extern std::map<int, const TCHAR *> core_st;
#endif

#endif /* __CORE_ST_H */
